version: "2.4"

networks:
  backend:

services:
  db:
    image: mariadb:10.5
#    ports:
#      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=RandomSecret
    networks:
      - backend

  appdbaas:
    ports:
      - 8080
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_PASS: RandomSecret

  sut:
    build:
      context: test
    networks:
      - backend
    depends_on:
      - appdbaas
