version: "2.4"

networks:
  backend:

services:
  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=RandomSecret
    networks:
      - backend

  appdbaas:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - backend
    environment:
      DB_HOST: db
      DB_PASS: RandomSecret

  sut:
#    image: php:7-alpine # Using baseimage from appdbaas for caching and curl
    build:
      context: test
#    entrypoint: ["sh","-c"]
#    entrypoint: ["echo",]
#    command: |
#      curl -f -s -d 'name=test&password=password' -XPOST http://appdbaas:8080/db/ && \
#      curl -f -s http://appdbaas:8080/db/
    networks:
      - backend
    depends_on:
      - appdbaas
